compatibility_date = "2025-03-14"

[[ env.development.d1_databases ]]
binding = "DB"
database_name = "microfeed-db"
database_id = "b75d69ff-dd12-403e-8fd7-b2e40a0e51c2"

[env.production]

[env.preview]
